php:
  preset: laravel
  disabled:
    - unused_use
  finder:
    exclude:
      - "modules"
      - "node_modules"
      - "storage"
      - "vendor"
    name: "*.php"
    not-name:
      - index.php
      - server.php
      - "*.blade.php"
      - "_ide_helper.php"
